// <auto-generated />
using System;
using ForexExchangeMonitoring.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForexExchangeMonitoring.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ForexCurrencyModelDbContext))]
    partial class ForexCurrencyModelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ForexExchangeMonitoring.Domain.DbModels.CurrencyModel", b =>
                {
                    b.Property<int>("CurrencyModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("currency_Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency_name");

                    b.HasKey("CurrencyModelId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("ForexExchangeMonitoring.Domain.DbModels.ForexCurrencyModel", b =>
                {
                    b.Property<int>("ForexCurrencyModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("forex_currency_model_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ExchangeRate")
                        .HasColumnType("float");

                    b.Property<int>("FromCurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("from_currency_id");

                    b.Property<DateTime>("LastRefreshedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToCurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("to_currency_id");

                    b.HasKey("ForexCurrencyModelId");

                    b.HasIndex("FromCurrencyId");

                    b.HasIndex("ToCurrencyId");

                    b.ToTable("RealTimeCurrencyExchangeRates");
                });

            modelBuilder.Entity("ForexExchangeMonitoring.Domain.DbModels.ForexCurrencyModel", b =>
                {
                    b.HasOne("ForexExchangeMonitoring.Domain.DbModels.CurrencyModel", "FromCurrency")
                        .WithMany("FromCurrencyIds")
                        .HasForeignKey("FromCurrencyId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ForexExchangeMonitoring.Domain.DbModels.CurrencyModel", "ToCurrency")
                        .WithMany("ToCurrencyIds")
                        .HasForeignKey("ToCurrencyId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("ForexExchangeMonitoring.Domain.DbModels.CurrencyModel", b =>
                {
                    b.Navigation("FromCurrencyIds");

                    b.Navigation("ToCurrencyIds");
                });
#pragma warning restore 612, 618
        }
    }
}
