// <auto-generated />
using System;
using ForexExchange.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForexExchange.Migrations
{
    [DbContext(typeof(RTCExchangeRateContext))]
    partial class RTCExchangeRateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ForexExchange.Models.RealTimeCurrencyExchangeRate", b =>
                {
                    b.Property<int>("RealTimeCurrencyExchangeRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FromCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastRefreshedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealTimeCurrencyExchangeRateId");

                    b.ToTable("RealTimeCurrencyExchangeRates");
                });
#pragma warning restore 612, 618
        }
    }
}
